import { Controller, ForbiddenException, Get, Param, UseGuards, Post, Body, HttpCode, HttpStatus } from "@nestjs/common";
import { User } from '@prisma/client'; //User Typescript type generated by Prisma
import { JwtGuard } from "../auth/guard";
import { GetUser } from "../auth/decorator"
import { UserService } from "./user.service";

@UseGuards(JwtGuard) //link this custom guard (check for jwt token for every user route of this controller) to our strategy named 'jwt' in file jwt.strategy.ts. 
@Controller('users') // définit la route "/users" de l'API
export class UserController {
	constructor (
		private userService: UserService
	) {}
	
	@Get()
	getUsers() {
		// console.log(this.userService.getUsers())
		return (this.userService.getUsers());
	}

	@Get('me') // GET /users/me
    getMe(@GetUser() user: User) {
        return user;
    }

	@Get('users/:id') //see nestjs doc on route parameters : https://docs.nestjs.com/controllers#route-parameters
	getUser(@Param('id') id: string) {
		console.log({id});
		const userId = parseInt(id);
		if ((isNaN(userId))) throw new ForbiddenException("incorrect id sent : not a number");
		const user = this.userService.getUser(userId);
		if (!user) {
			throw new ForbiddenException("No user found with given id");
		}
		console.log({user});
		return (user);
	}

	@HttpCode(HttpStatus.OK)
	@Get('score')
	async getScore(
		@GetUser() user
	) {
		console.log({user});
		const score = await this.userService.getScore(user.sub);
  		return { score: score }; 
	}

	@HttpCode(HttpStatus.OK)
	@Post('score')
	async updateScore(
		  @Body() body: { score: number },
		  @GetUser() user
	 	) {
		  const { score } = body;
		  console.log({score});
		  console.log({user});
		  await this.userService.updateScore(score, user.sub);
	}
}