// import { Message, User } from "@prisma/client";

import { Chat, ChannelInfo, ChannelMutedUsers, ChannelStatus, User, Message } from '@prisma/client'; //User Typescript type generated by Prisma


export type MutedUser = ChannelMutedUsers & {
	user: User
}

export type AllChannelInfo = ChannelInfo & {
	bannedUsers: User[],
	mutedUsers: MutedUser[],
	administrators: User[],
}

export type ChatAndParticipants = Chat & { participants : User[] }
export type ChatAndParticipantsAndMsgs = ChatAndParticipants & { messages: Message[]} 
export type AllChatInfo = ChatAndParticipantsAndMsgs & {channelInfo: AllChannelInfo}

export type MutedUsersAndChannelInfo = ChannelMutedUsers & {
	channel: {
		chat: {participants: User[]},
		administrators: User[],
		bannedUsers: User[]	
	}
}