import { Controller, ForbiddenException, Get, Post, Param, UseGuards, Body, Res, Request, Req } from "@nestjs/common";
import { User } from '@prisma/client'; //User Typescript type generated by Prisma
import { JwtGuard } from "../auth/guard";
import { GetUser } from "../auth/decorator"
import { ChatService } from "./chat.service";
import { CreateChatDto } from "./dto";

@UseGuards(JwtGuard) //link this custom guard (check for jwt token for every user route of this controller) to our strategy named 'jwt' in file jwt.strategy.ts.
@Controller('chats') // définit la route "/chats" de l'API
export class ChatController {
	constructor (
		private chatService: ChatService
	) {}

	@Post('create')
	createChat(
		@GetUser() creator,
        @Body() payload,
    ) {
		const participants = [...payload.recipients, creator.sub];
		return (this.chatService.createChat(participants, creator.sub));
	}

	@Post('findByParticipants')
	findChatByParticipants(
		@GetUser() creator,
        @Body() payload,
    ) {
		const participantIds = [...payload.recipients, creator.sub];
		return (this.chatService.findChatByParticipants(participantIds));
	}

	@Get('findById/:id')
	findChatById(@Param('id') id: string,) {
		const chatId = parseInt(id);
		if ((isNaN(chatId)))
			throw new ForbiddenException("incorrect id sent : not a number");
		return (this.chatService.findChatById(chatId));
	}

	@Post('findOrCreate')
	findOrCreateChat(
		@GetUser() creator,
        @Body() payload,
    ) {
		try {
			const participantIds = [...payload.recipients, creator.sub];
			const participantIdsNoDuplicates = [...new Set(participantIds)]
			if (participantIdsNoDuplicates.length < 2)
			throw new ForbiddenException('Cannot findOrCreate Chat with 1 user',);
			return (this.chatService.findOrCreateChat(participantIdsNoDuplicates, creator.sub));
		} catch (error) {
			throw error;
		}
	}

	@Get('findAllMyChats')
	findAllMyChats(@GetUser() me) {
		return (this.chatService.findAllMyChats(me));
	}

}
